package:
  name: dryfalls
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/pythonflaskserverapps/dryfalls.git

requirements:
  build:
    - python
    - setuptools
  run:
    

test:
  imports:
    - dryfalls

about:
  home: https://github.com/pythonflaskserverapps/dryfalls
  license: MIT
  license_file: LICENSE
