package:
  name: dryfalls
  version: "0.0.13"

source:
  git_rev: v0.0.13
  git_url: https://github.com/pythonflaskserverapps/dryfalls.git

requirements:
  build:
    - python
    - setuptools
  run:
    - pyyaml==3.13
    - pygithub==1.43.5

test:
  imports:
    - dryfalls

about:
  home: https://github.com/pythonflaskserverapps/dryfalls
  license: MIT
  license_file: LICENSE
